### ISSUE TITLE
packaged release?

### ISSUE THREAD

**Issue by ssexton71** [Plaristote/crails#3]
A packaged release would be nice.   Building it with cmake doesn't seem to work... or maybe some instructions are missing?

**Comment by Plaristote** [comment]
It wasn't really in my schedule up until now... if you happen to use Archlinux, I could probably quickly set up a crails-git package in AUR.

Otherwise, I'll have to work on our building tools first. There's a considerable amount of work left to do until we're ready to generate packages (such a process will use the crails-docker module, and I still have a lot of work to do on that module).

Anyhow, building with cmake should work. But maybe some instructions are indeed missing ! Can cmake properly configure the project, or does it fail during the compilation ? Can you show me some console output ?

**Comment by ssexton71** [comment]
I'm sure building with cmake works, if you can sort out the dependencies.   Which I didn't get very far with, at all.  The issues I encountered were:

1.  cpp-netlib does not have any build instructions.  You have to reverse their build script to figure out the needed environment variables.   Granted this isn't a crails problem, but it does get in the way of trying to evaluate crails.   

2.  crails wants CPPNETLIB_INCLUDE to point to cpp-netlib's boost directory.  This isn't at all obvious if you are unfamiliar with cpp-netlib.

3.  ODB isn't actually optional.  cmake won't generate the makefiles if it is missing.

At this point I stopped.  I don't need ODB for my current project and I did not want to find out how many other unneeded dependencies I'd have to work through just to get it to compile.

**Comment by ssexton71** [comment]
Put another way, your build instructions have some prerequisites that aren't clear.   Your readme has this:

cmake ..
make
sudo make install

But this only works if all the dependencies are in the 'right' place, where cmake can find them.  Otherwise you end up with this:

cmake -DCPPNETLIB_INCLUDE=path-to-cppnetlib-boost-dir -DCPPNETLIB_LIB=path-to-cppnetlib-archive-lib  (more vars for ODB?  mongo?  others?) ..

**Comment by Plaristote** [comment]
Well, in order to compile cpp-netlib, you can use the script I wrote for our docker machines:
https://github.com/Plaristote/crails/blob/master/modules/docker/app/docker/base/compile-cppnetlib.sh
It uses an old version of cpp-netlib.

I'm not sure I've tested crails with cpp-netlib 0.12 (which is probably what you downloaded, since it's the current stable version). It does work with version 0.11 (which is the version used by the previous script), and with version 0.13 (which is the version I use on my personal machine).

The easiest thing for you to do is probably just to use the script, and use cpp-netlib 0.11. It's not so dramatic to use an out-dated version if it's just for testing purposes.

#### CMake find_package
To solve our dependencies, both cpp-netlib and us use cmake's `find_package` function.

Most development packages, such as boost, are provided with `Find[packagename].cmake` files that cmake then uses to find dependencies. By default, cmake will look for packages using the files provided by your own system's packagers (or that you have installed yourself).

As developers, we can also provide our own finding files, and tell cmake where to look for them. That's what we do with crails, in order for it to find cpp-netlib.

So you shouldn't need to set any particular variable to find boost or cpp-netlib. All of that is already built-in.

#### Modules dependencies
As for our module dependencies, we don't really "find" them. We assume they can already be found in the linking and include paths (`/usr/lib`, `/usr/local/lib`, `/usr/include` and `/usr/local/include`).

There are two exceptions:
`crails-image`, because ImageMagick provides cmake finding files.
`crails-odb`, for the same reason.

I've never had issues with crails-image... ImageMagick is a pretty standard package after all.

As for ODB, sometimes the find_package feature didn't work with it... but really, we only use it to make sure that ODB is indeed available in the system : if you know that it is, and the find_package just reports not finding it, then you should just remove the find_package line in the `modules/odb/CMakeLists.txt` file.

If you wish to use ODB, I know that ubuntu provides packages for it... but I've never tried to link to those, so just in case, you may want to compile ODB yourself.
The compilation process is pretty straightforward, but you need to compile at least 4 different packages, so the script we use in our docker machine may be helpful:
https://github.com/Plaristote/crails/blob/master/modules/docker/app/docker/base/compile-odb.sh
Note that this script only compiles odb support for postgresql libraries.

#### Disabling modules
The MongoDB and ODB modules are compiled by default... but you may not have the required dependencies installed. If you don't care about those, you can disable them.

Just use the `-DUSE_MONGODB=OFF` and or `-DUSE_ODB=OFF` options when configuring the project with cmake.

#### Notes
You used MongoDB in one of your example : I should warn you, the MongoDB module isn't documented, and it's not up to date. I'm currently re-writing it to use the new mongocxx driver (the module was written years ago, and back then the legacy mongocxx driver was still the norm).

The ODB module is stable (at least with postgresql databases, we've been using it in production environment for several years already). It's up to date, and it's documented (not entirely documented, but enough that it should be possible to use it).

If you want to use MongoDB, I recommend directly using the mongocxx driver.
If you want to use ODB, our module can probably make things easier for you.

**Comment by Plaristote** [comment]
Hi again @ssexton71 !
If you're still interested, this issue has been fixed with the new release of the framework.

We moved away from CMake and embrassed [build2](https://build2.org), which takes care of downloading and building our dependencies.

So, technically, there is a package now. Though it is (sort of) a source package. It's much better for us, as build2 implements package management (a bit like npm or pip would), build management, and supports most platforms. One package to rule them all.
There are still dependencies not managed by build2... but nothing vital. Just make sure `libssh-dev` (or `libssh-devel`) is installed on your system if you wanna try out the deployment tool: it's pretty useful !

We also have an install script now, which has been tested on Fedora, Ubuntu and FreeBSD (and should work with Mac):
[Installing on Linux, FreeBSD and MacOS](https://crails-framework.github.io/website/getting-started/linux.html)

And we have a bunch of tutorials... many more to come, but the basics are covered:
[Getting Started](https://crails-framework.github.io/website/getting-started/)
